title: Taoufik's Portfolio
description: Business Information Technology Graduate | Data & Business Analyst | AI Enthusiast
theme: jekyll-theme-minimal

# Optional: Add your information
author: Taoufik
email: your.email@example.com
linkedin: your-linkedin-username
github: your-github-username

# Show downloads button
show_downloads: false
