title: Taoufik Brinis
description: Business & Data Analyst | AI Innovation & Digital Transformation

# Use minimal theme (has sidebar)
theme: jekyll-theme-minimal

# Personal Information (shows in sidebar)
logo: https://github.com/TaoufikBrinis/Taoufik_portfolio.github.io/blob/main/profile1.png
email: taoufik.brinis@gmail.com

# Social Links (shows in sidebar)
github_username: TaoufikBrinis
linkedin_username: taoufik-brinis-1b185a211

# Show/Hide Elements
show_downloads: false

# Additional Settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
