title: Taoufik Brinis
description: Business & Data Analyst | AI Innovation & Digital Transformation
theme: jekyll-theme-minimal

# Personal Information
logo: /profile1.png
email: taoufik.brinis@gmail.com

# Social Links
github_username: TaoufikBrinis
linkedin_username: taoufik-brinis-1b185a211

# Show/Hide Elements
show_downloads: false



# Additional Settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
