title: Taoufik Brinis
description: Business & Data Analyst | AI Innovation & Digital Transformation
remote_theme: pages-themes/cayman@v0.2.0

show_downloads: false

markdown: kramdown

plugins:
  - jekyll-remote-theme
